# Generated by Django 6.0.6 on 2026-07-04 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Ordine')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='pending', max_length=20, verbose_name='Stato')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prezzo Totale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Prodotto')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantità Disponibile')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Immagine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Aggiunta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Ordine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Prodotto')),
            ],
        ),
    ]
